name: manager_key
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  geolocator: ^11.0.1
  http: ^1.1.0
  mobile_scanner: ^6.0.1
  connectivity_plus: ^5.0.1
  provider: ^6.0.0
  google_maps_flutter: ^2.14.0
  quickalert: ^1.1.0
  permission_handler: ^11.0.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ✅ CONFIGURACIÓN DE ICONOS
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icono_sereci.png"
  adaptive_icon_background: "assets/icon/fondo_adaptive.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icono_sereci.png

  # ✅ ASSETS (Si necesitas agregar imágenes)
  # assets:
  #   - assets/icon/
  #   - assets/images/